### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zetok** [JSchilli1/poomf.sh#11]
As it is currently, poomf.sh is a proprietary code, since that's what missing license means.
I think that it's not the desired state of things?

If you are not sure which one to pick, there's https://tldrlegal.com/

Depending on what you want, you most likely may want to pick one of "main" licenses:
* [MIT](https://tldrlegal.com/license/mit-license)
* [BSD](https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29)
* [LGPL-2.1](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-%28lgpl-2.1%29)

Or, if you want my biased opinion, just simply go with [GPLv3](https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29) :3

CC-ing contributors listed by GH (sorry if I missed someone):
@Epictek 
@ooploopl- 
@Sarkynin 
@arianon 
@DanielFGray 
@JSchilli1

**Comment by JSchilli1** [comment]
Thanks for the heads up!
