### ISSUE TITLE
Pomf.se upload doesn't work

### ISSUE THREAD

**Issue by installgen2** [JSchilli1/poomf.sh#7]
Uploading using pomf.se doesn't work anymore, changing it back to http fixes it though

**Comment by JSchilli1** [comment]
I'm not sure what to do, both work for me. The user who opened pull request #6 says HTTP doesn't work for him. I'd prefer to use HTTPS, as it's secure, but if more people are having this problem I guess I should revert it.

**Comment by installgen2** [comment]
Doesn't work for me on a fresh Fedora installation, nor does it work on another computer I have running Debian, I'll see if I can figure out what the actual problem is.

**Comment by Epictek** [comment]
could you change the curl line to this and see what output you get.
`pomf=$(curl -f -F files[]="@${FILE}" "https://pomf.se/upload.php?output=gyazo")`

**Comment by installgen2** [comment]
`curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).`

but if I make it `pomf=$(curl --ciphers ecdhe_ecdsa_aes_256_sha -f -F files[]="@${FILE}" "https://pomf.se/upload.php?output=gyazo")` it works fine, I think it's a bug with some versions of curl that means cloudflare issued HTTPS certificates often don't work unless you specify supported ciphers, honestly I don't understand any of this.

Oh, a toggle for HTTPS would still be nice though,

**Comment by JSchilli1** [comment]
Added an HTTPS option, thanks for the report.
